{"name": "User gets login with wrong email or password", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/login\", waiting until \"networkidle\"", "trace": "self = <tests.authentification.test_authorization.TestAuthorization object at 0x0000023FCC057690>, login_page = <pages.authentification.login_page.LoginPage object at 0x0000023FCE4996D0>, email = '  ', password = 'password'\n\n    @pytest.mark.parametrize(\n        \"email, password\",\n        [\n            (\"user.name@gmail.com\", \"password\"),\n            (\"user.name@gmail.com\", \"  \"),\n            (\"  \", \"password\")\n        ]\n    )\n    @allure.title('User gets login with wrong email or password')\n    @allure.severity(Severity.CRITICAL)  # Добавили severity\n    def test_wrong_email_or_password_authorization(self, login_page: LoginPage, email: str, password: str):\n>       login_page.visit(AppRoute.LOGIN)\n\ntests\\authentification\\test_authorization.py:65: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\base_page.py:14: in visit\n    self.page.goto(url, wait_until='networkidle')\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9024: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x0000023FCC043620>, cb = <function Channel.send.<locals>.<lambda> at 0x0000023FCC5AE660>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE           Call log:\nE             - navigating to \"https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/login\", waiting until \"networkidle\"\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "steps": [{"name": "Opening the url \"AppRoute.LOGIN\"", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/login\", waiting until \"networkidle\"\n\n", "trace": "  File \"C:\\Users\\tvbel\\PycharmProjects\\autotests-ui\\pages\\base_page.py\", line 14, in visit\n    self.page.goto(url, wait_until='networkidle')\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tvbel\\PycharmProjects\\autotests-ui\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9024, in goto\n    self._sync(\n    ~~~~~~~~~~^\n        self._impl_obj.goto(\n        ^^^^^^^^^^^^^^^^^^^^\n            url=url, timeout=timeout, waitUntil=wait_until, referer=referer\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        )\n        ^\n    )\n    ^\n  File \"C:\\Users\\tvbel\\PycharmProjects\\autotests-ui\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"C:\\Users\\tvbel\\PycharmProjects\\autotests-ui\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tvbel\\PycharmProjects\\autotests-ui\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\tvbel\\PycharmProjects\\autotests-ui\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n    )\n    ^\n  File \"C:\\Users\\tvbel\\PycharmProjects\\autotests-ui\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1751958868009, "stop": 1751958898081}], "parameters": [{"name": "page", "value": "'Browser.FIREFOX'"}, {"name": "email", "value": "'  '"}, {"name": "password", "value": "'password'"}], "start": 1751958868008, "stop": 1751958898083, "uuid": "b06e3ffd-0d24-4498-9b65-91c4722f03e1", "historyId": "073e023f8f0fb4a8b16b55d2a1303c26", "testCaseId": "a9b82e0b6fbbc3b583dcbf80f339f829", "fullName": "tests.authentification.test_authorization.TestAuthorization#test_wrong_email_or_password_authorization", "labels": [{"name": "story", "value": "Authorization"}, {"name": "subSuite", "value": "Authorization"}, {"name": "suite", "value": "Authentication"}, {"name": "feature", "value": "Authentication"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "AUTHORIZATION"}, {"name": "epic", "value": "LMS system"}, {"name": "tag", "value": "REGRESSION"}, {"name": "parentSuite", "value": "LMS system"}, {"name": "tag", "value": "authorization"}, {"name": "tag", "value": "regression"}, {"name": "host", "value": "LAPTOP-CUJR72I1"}, {"name": "thread", "value": "13792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.authentification.test_authorization"}]}